-- NOTE:
--   Use ANSI-compliant column definitions so the migration works on
--   both PostgreSQL (production) and H2 (dev/test). Application code
--   is responsible for updating the updated_at column when entities
--   change, therefore no trigger is required here.
CREATE TABLE tool_approval_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_id VARCHAR(255) NOT NULL,
    tool_name VARCHAR(255) NOT NULL,
    policy VARCHAR(20) NOT NULL DEFAULT 'always',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Unique constraint: one policy per server+tool combination
    CONSTRAINT uk_server_tool UNIQUE (server_id, tool_name),

    -- Foreign key to mcp_servers with CASCADE delete
    CONSTRAINT fk_tool_policy_server FOREIGN KEY (server_id)
        REFERENCES mcp_servers(server_id) ON DELETE CASCADE
);

-- Index for fast lookups by server
CREATE INDEX idx_tool_policies_server ON tool_approval_policies(server_id);
